### ISSUE TITLE
Post image as the link

### ISSUE THREAD

**Issue by Ruriko** [kabutor/rss-to-reddit#1]
Is it possible to make it use the image url from RSS as the link for reddit?

**Comment by kabutor** [comment]
I don't think it's possible, when you sumbit something to reddit (manually or via the API) you can only submit, text (no image), a picture(and then only the picture is shown) or a URL, that is what I use on the script.

When you submit a URL, reddit parses the URL and pick some picture, don't know how it's done, if it's youtube it picks the same thumb as the one on youtube, but on other websites I don't know how it chooses it, but you can not change it, as far as I know.

I'm gonna update the Readme because it's the second time someone asked me this :)
